### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by MattDMo** [sublimelsp/LSP-PowerShellEditorServices#10]
Can you push out a new release including the changes made in the last several months? Also, FYI, the [latest server version](https://github.com/PowerShell/PowerShellEditorServices/releases) is now 2.5.3, so you may want to change that in the settings as well. I can submit a PR if you really want me to 😁

**Comment by MattDMo** [comment]
I just looked further down in my own link and saw that 3.0.3 is out as well. I have no idea if v3 introduces breaking changes - something to investigate...

**Comment by deathaxe** [comment]
Server has been updated to 3.4.2

That said, you can select the server version to install via `Preferences: LSP-PowerShellEditorServices Settings`

https://github.com/sublimelsp/LSP-PowerShellEditorServices/blob/f3eca0e7d28b7dc17b88c87f65893ab4fa89fc07/LSP-PowerShellEditorServices.sublime-settings#L6
