### ISSUE TITLE
[ST4] Clicking on "Show documentation for: ..." throws error

### ISSUE THREAD

**Issue by God-damnit-all** [sublimelsp/LSP-PowerShellEditorServices#13]
![image](https://github.com/sublimelsp/LSP-PowerShellEditorServices/assets/53661808/4f741a4e-f7ea-43db-b23a-dd7ecce9773f)
When I click this, I get an error:

![image](https://github.com/sublimelsp/LSP-PowerShellEditorServices/assets/53661808/50992452-e8e3-40b6-b0cf-3674bc135790)

**Comment by deathaxe** [comment]
In which context does the annotation show up? Can you provide any code snippet?
