### ISSUE TITLE
[FR] PSScriptAnalyzerSettings.psd1 hierarchy

### ISSUE THREAD

**Issue by God-damnit-all** [sublimelsp/LSP-PowerShellEditorServices#16]
I would like it if PSScriptAnalyzerSettings.psd1 was checked for based on a hierarchy: 

* Highest priority would be the workspace folder
* Next to highest priority would be the the `Packages/User` folder
* Previous to lowest priority would be the `powershell.scriptAnalysis.settingsPath` setting
* Lowest priority would be the `Packages/LSP-PowerShellEditorServices` folder

Alternatively, have `powershell.scriptAnalysis.settingsPath` be an array with this as part of the default sublime-settings file:

```text
		"powershell.scriptAnalysis.settingsPath": [
			"PSScriptAnalyzerSettings.psd1",
			"${packages}/User/PSScriptAnalyzerSettings.psd1",
			// "Recommended/placement/of/an/absolute/path",
			"${packages}/LSP-PowerShellEditorServices/PSScriptAnalyzerSettings.psd1",
		]
```

**Comment by deathaxe** [comment]
This helper package just provides a frontend for existing features of PowerShellEditorServices language server.

A feature request to use and maybe merge various settings files should probably be filed at language server's repository instead.

**Comment by deathaxe** [comment]
The point is `powershell.scriptAnalysis.settingsPath` to be a server-side setting to specify the configuration file. This plugin just provides a frontend for end users to modify it. The value is forwarded to the server as is without further evaluation.

It's up to the server to expand relative paths and lookup the file. The client (LSP / this plugin) is not involved.

- Relative paths are resolved relative to root of workspace folders, by server. 
- Absolute paths can be used to force a certain file to be used.

As a workspace can contain multiple folders the server knows best which folder to search the file in, at any given time.

However project-specific settings can be used to create a lookup hierarchy.

1. A generic fallback can be defined in `LSP-PowerShellEditorServices.sublime-settings`

   ```json
   {
      "settings":
      {
         "powershell.scriptAnalysis.settingsPath": "${packages}/User/PSScriptAnalyzerSettings.psd1",
      },
   }
   ```

2. A project-specific override can be specified via `<Name>.sublime-project`

   ```json
   {
      "folders": [
         {
            "path": ".",
         },
      ],
      "settings":
      {
         "LSP":
         {
            "PowerShellEditorServices": {
               "settings": {
                  "powershell.scriptAnalysis.settingsPath": "PSScriptAnalyzerSettings.psd1",
               },
            },
         },
      },
   }
   ```

> **Note**
>
> 1. It's unlikely LSP-PowerShellEditorServices will provide a `PSScriptAnalyzerSettings.psd1`, thus related hierarchy is not relevant.
> 
> 2. All settings in `LSP-PowerShellEditorServices.sublime-settings` are server defaults. So the value of `powershell.scriptAnalysis.settingsPath` is. As it is not intended to mess with users' project settings a hierarchy is to be set-up by users manually.
> 
> 3. The illustrated strategy of using project-specific settings is aligned with VS Code's strategy of using workspace settings. The main difference is just VS Code using a `.vscode/settings.json` and ST relies on `*.sublime-project` files.
