### ISSUE TITLE
Plugin can't start with `pwsh`, only with `powershell`

### ISSUE THREAD

**Issue by Paciupa** [sublimelsp/LSP-PowerShellEditorServices#27]
- I faced the same behavior on two machines (Win 10 and Win 11).
- Both `PowerShell 5` and `PowerShell 7` are installed and work.
- Plugins `PowerShell`, `LSP` and `LSP-PowerShellEditorServices` are installed successfully (but not `PowerShellEditorServices`).
- `Tools -> Developer -> Show Scope Name` shows `source.powershell` (.ps1 file).
- Every other LSP plugin works (ruff, pyright, css, json, markdown, bash).
- `log_debug: true` set in `User/LSP/LSP.sublime-settings`.

When `powershell_exe` is empty or set to `pwsh` or set to `C:\\Program Files\\PowerShell\\7\\pwsh.exe`:

- Plugin can't download and start `PowerShellEditorServices`
- LSP Log Panel and Sublime Console (with `log_debug: true`) don't report any errors.
- `LSP: Troubleshoot server` can't start showing just `Running server test`.
- *After that, all LSP plugins are broken.*

When `powershell_exe` is set to `powershell` or `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`:

- Plugin tries to download and start `PowerShellEditorServices`.
- ~~`PowerShellEditorServices` had crashed every start time~~. It happened because of Execution Policy.
- Everything works!

I couldn't recreate the bug in Sublime Safe Mode since ~~the `LSP` plugin can't be installed without restarting Sublime Text (`Package Control: The dependency 'typing_extensions' is not available`)~~ plugin can't download and start `PowerShellEditorServices`.

In Windows Sandbox, both (`pwsh` and `powershell`) work fine with freshly installed `PowerShell 7`, `Sublime Text`, etc.

I've also tried to debug this issue by executing and modifying some parts of the plugin code... so what I've found:

- One unclear suspicious message in the Sublime console (without making any modifications): `Parse Error at line 258 column 17: closing p does not match opening not`. I'm not sure if it's relevant.
- Sometimes `sublime.load_settings("LSP-PowerShellEditorServices.sublime-settings")` can't read default settings, only User settings. I suppose it happened when the plugin crashed and unloaded, so it doesn't help.
- **The most interesting thing**. Every time after restarting Sublime or disabling and enabling the plugin, a hanging `pwsh` process remains with such CommandLine:
```powershell
[System.Diagnostics.FileVersionInfo]::GetVersionInfo(\"C:\Users\Jan\AppData\Local\Sublime Text\Package Storage\LSP-PowerShellEditorServices\PowerShellEditorServices\bin\Common\Microsoft.PowerShell.EditorServices.dll\").FileVersion
```
So I think the problem may be in the `needs_update_or_installation()` function on [lines 36-37](https://github.com/sublimelsp/LSP-PowerShellEditorServices/blob/0a75a4670275f12827c310f5a0752099d069f61d/plugin.py#L36-L37). And when I was trying to call `cls.run()` manually from Sublime, it hung all Sublime.

**Comment by deathaxe** [comment]
This helper package installs v3.12.0 by default.

https://github.com/sublimelsp/LSP-PowerShellEditorServices/blob/0a75a4670275f12827c310f5a0752099d069f61d/LSP-PowerShellEditorServices.sublime-settings#L6

Maybe that one is not compatible with pwsh.

I run those on pwsh 7 for ages with following user config. Just recently updated to 4.0

```
{
	"powershell_exe": "pwsh.exe",
	"version": "4.0.0",
}
```

**Comment by Paciupa** [comment]
Yes, when I mock [line 37](https://github.com/sublimelsp/LSP-PowerShellEditorServices/blob/0a75a4670275f12827c310f5a0752099d069f61d/plugin.py#L37) with `version_info = "3.12.0.0\r\n"` everything works. So problem is here.

**Comment by Paciupa** [comment]
> This helper package installs v3.12.0 by default.
> 
> https://github.com/sublimelsp/LSP-PowerShellEditorServices/blob/0a75a4670275f12827c310f5a0752099d069f61d/LSP-PowerShellEditorServices.sublime-settings#L6
> 
> Maybe that one is not compatible with pwsh.
> 
> I run those on pwsh 7 for ages with following user config. Just recently updated to 4.0
> 
> ```
> {
> 	"powershell_exe": "pwsh.exe",
> 	"version": "4.0.0",
> }
> ```

I think the problem is connected with subprocess calling that read dll version.

**Comment by deathaxe** [comment]
Next release will add a timeout in case version check gets stuck.

**Comment by Paciupa** [comment]
I am not sure it will help. 

<details>
<summary>Here is the code showing difference between `powershell_exe = "powershell"` and `powershell_exe = "pwsh"`  </summary>
```python
import subprocess

import sublime_plugin


class MyTest2Command(sublime_plugin.TextCommand):

    @classmethod
    def run2(cls, *args, **kwargs) -> bytes:
        platform = "windows"
        if platform == "windows":
            startupinfo = subprocess.STARTUPINFO()  # type: ignore
            flag = subprocess.STARTF_USESHOWWINDOW  # type: ignore
            startupinfo.dwFlags |= flag
        else:
            startupinfo = None
        return subprocess.check_output(args=args, cwd=kwargs.get("cwd"), startupinfo=startupinfo)

    @classmethod
    def run(cls, edit):
        # powershell_exe = "powershell"
        powershell_exe = "pwsh"
        dll_path = "C:\\Users\\Jan\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-PowerShellEditorServices\\PowerShellEditorServices\\bin\\Common\\Microsoft.PowerShell.EditorServices.dll"
        cmd = '[System.Diagnostics.FileVersionInfo]::GetVersionInfo("{}").FileVersion'.format(dll_path)
        print(f"{cmd=}")
        version_info_mocked = "3.12.0.0\r\n"
        print(f"{version_info_mocked=}")
        version_info = cls.run2(powershell_exe, "-Command", cmd).decode('ascii')
        print(f"{version_info=}")
```

</details>

**Comment by deathaxe** [comment]
The version check command line runs fine on both powershell and pwsh on my end as language server does. I have been using v3.20.0 since it has been released on both interpreters without issues.

**Comment by Paciupa** [comment]
Thank you, the new version works with `pwsh`!
The troubleshooting reports ```[Errno 13] Permission denied: 'C:\\Users\\Jan\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-PowerShellEditorServices\\PowerShellEditorServices\\bin\\Common\\MediatR.dll'``` and subprocess call raises `subprocess.TimeoutExpired`, but `PowerShellEditorServices` are still working.

Also, thanks for the great plugin!

**Comment by deathaxe** [comment]
I've seen that once when trying to update, too. Most likely the old server still wasn't stopped completely, when update arived. Windows is prettry restrictive and locks used libraries.
